services:

  mongodb:
    image: mongo:latest
    container_name: cotecnova-mongo
    ports:
      - "27017:27017"

  soap-service:
    build: ./soap-legacy-node
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cotecnova
    depends_on:
      - mongodb
    container_name: cotecnova-soap

  rest-api:
    build: ./rest-api-python
    # Lo exponemos en el puerto 8001 para que no choque con Node
    ports:
      - "8001:8000"
    environment:
      - SOAP_WSDL_URL=http://soap-service:8000/wsdl?wsdl
    depends_on:
      - soap-service
    container_name: cotecnova-rest